export const authAppearance = {
  options: {
    logoPlacement: "none" as const,
  },
  variables: {
    colorPrimary: "var(--yellow)",
    colorForeground: "var(--ink)",
    colorMutedForeground: "var(--muted)",
    colorBackground: "transparent",
    colorInputBackground: "var(--surface)",
    colorInputForeground: "var(--ink)",
    colorBorder: "var(--line)",
    borderRadius: "0",
    fontFamily:
      'ui-monospace, "SFMono-Regular", "Cascadia Code", "Liberation Mono", Menlo, monospace',
    fontFamilyButtons:
      'ui-monospace, "SFMono-Regular", "Cascadia Code", "Liberation Mono", Menlo, monospace',
    spacing: "0.75rem",
  },
  elements: {
    rootBox: { width: "100%" },
    cardBox: { width: "100%", boxShadow: "none" },
    card: {
      width: "100%",
      padding: "0",
      gap: "0.75rem",
      background: "transparent",
      boxShadow: "none",
      border: "0",
    },
    header: { display: "none" },
    main: { gap: "0.75rem" },
    form: { gap: "0.75rem" },
    formField: { gap: "0.35rem" },
    formFieldLabel: {
      color: "var(--ink)",
      fontSize: "0.75rem",
      fontWeight: "800",
      letterSpacing: "0.04em",
    },
    formFieldInput: {
      minHeight: "44px",
      border: "1px solid var(--line)",
      background: "var(--surface)",
      color: "var(--ink)",
      boxShadow: "none",
      fontSize: "0.875rem",
    },
    formButtonPrimary: {
      minHeight: "44px",
      border: "1px solid var(--ink)",
      background: "var(--yellow)",
      color: "#151515",
      boxShadow: "none",
      fontSize: "0.75rem",
      fontWeight: "900",
      letterSpacing: "0.08em",
      textTransform: "uppercase" as const,
    },
    formFieldAction: { color: "var(--red)", fontWeight: "800" },
    footer: {
      marginTop: "0.25rem",
      padding: "0.75rem 0 0",
      borderTop: "1px solid var(--line)",
      background: "transparent",
    },
    footerAction: { gap: "0.35rem", fontSize: "0.75rem" },
    footerActionText: { color: "var(--muted)" },
    footerActionLink: { color: "var(--red)", fontWeight: "900" },
    footerPages: {
      marginTop: "0.35rem",
      color: "var(--muted)",
      fontSize: "0.625rem",
      opacity: "0.65",
    },
    identityPreview: {
      border: "1px solid var(--line)",
      background: "var(--surface)",
      boxShadow: "none",
    },
    otpCodeFieldInput: {
      border: "1px solid var(--line)",
      background: "var(--surface)",
      color: "var(--ink)",
      boxShadow: "none",
    },
    alert: {
      border: "1px solid var(--red)",
      background: "var(--err-soft)",
      color: "var(--ink)",
    },
  },
}
